# Ultralight
ul-base: /ul
ul-banner: img/2011/Welsh-3000ers/banner.jpg
permalink: /:categories/:year/:title

# Software Development
theme: jekyll-theme-cayman
title: [Jonathan Price]
description: [Making things with Software]
show_downloads: false
google_analytics: [UA-36562901-4]
github:
  is_project_page: false
